# Generated by Django 4.2.14 on 2024-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(default='Participant', max_length=122, verbose_name='Position'),
        ),
    ]
