# Generated by Django 4.2.14 on 2024-08-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_eventinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(max_length=122, verbose_name='Position'),
        ),
    ]
