# Generated by Django 4.2.14 on 2024-08-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_formdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='eventinfo',
        ),
    ]
