# Generated by Django 4.2.14 on 2024-08-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_formdata_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
