# Generated by Django 4.2.14 on 2024-08-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_formdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinformation',
            old_name='about',
            new_name='eventabout',
        ),
        migrations.RenameField(
            model_name='eventinformation',
            old_name='date',
            new_name='eventdate',
        ),
        migrations.RenameField(
            model_name='eventinformation',
            old_name='day',
            new_name='eventday',
        ),
        migrations.RenameField(
            model_name='eventinformation',
            old_name='file',
            new_name='eventfile',
        ),
        migrations.RenameField(
            model_name='eventinformation',
            old_name='time',
            new_name='eventtime',
        ),
    ]
