# Generated by Django 4.2.14 on 2024-08-25 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_eventinformation_fileurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormData',
        ),
    ]
