# Generated by Django 4.2.14 on 2024-10-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_draftmodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='draftmodel',
            old_name='draft',
            new_name='data',
        ),
    ]
