# Generated by Django 4.2.4 on 2025-01-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_draft_draftmodel_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinformation',
            name='eventfile',
        ),
        migrations.RemoveField(
            model_name='eventinformation',
            name='fileurl',
        ),
    ]
