# Generated by Django 4.2.4 on 2025-01-11 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
    ]
