# Generated by Django 4.2.14 on 2025-01-12 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
