# Generated by Django 4.2.14 on 2025-01-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_answerprofile_answers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdata',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
