# Generated by Django 4.2.14 on 2025-01-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_formdata_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnswerProfile',
        ),
    ]
