# Generated by Django 4.2.14 on 2025-01-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='username',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
