# Generated by Django 4.2.14 on 2025-01-14 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_answers_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventInformation',
            new_name='FormInfo',
        ),
    ]
