# Generated by Django 4.2.14 on 2025-01-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_eventinformation_forminfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='user',
        ),
    ]
