# Generated by Django 4.2.14 on 2025-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='detect',
            field=models.BooleanField(default=False),
        ),
    ]
